#!/bin/bash
#
#	/etc/rc.d/init.d/csync2-inotify
#
# chkconfig: - 80 30
# description: Starts an inotifywait process for csync2
# processname: csync2-inotify
# 

pidfile=${PIDFILE-/var/run/csync2-inotify.pid}
lockfile=${LOCKFILE-/var/lock/subsys/csync2-inotify}
progfolder=/usr/local/bin/
progfile="csync2-inotify"
progname="$progfolder/$progfile"
RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

# Source function library.
. /etc/init.d/functions

start() {
	echo -n "Starting csync2-inotify: "
	daemon --pidfile=${pidfile} $progname
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && touch ${lockfile}
        return $RETVAL
}	

stop() {
	echo -n "Shutting down csync2-inotify: "
        killproc -p ${pidfile} -d ${STOP_TIMEOUT} $progname
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}

}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
        status -p ${pidfile} $progname
        RETVAL=$?
	;;
    restart)
    	stop
	start
	;;
    reload)
        LSB=1 killproc -p ${pidfile} $progfile -HUP
	;;
    *)
	echo "Usage: $progfile {start|stop|status|reload|restart}"
	exit 1
	;;
esac
exit $?
